//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.OnlineForms;
using CMS.OnlineForms.Types;

[assembly: RegisterBizForm(Form_2026_05_27_16_08_51_576Item.CLASS_NAME, typeof(Form_2026_05_27_16_08_51_576Item))]

namespace CMS.OnlineForms.Types
{
	/// <summary>
	/// Represents a content item of type Form_2026_05_27_16_08_51_576Item.
	/// </summary>
	public partial class Form_2026_05_27_16_08_51_576Item : BizFormItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BizForm.Form_2026_05_27_16_08_51_576";


		/// <summary>
		/// The instance of the class that provides extended API for working with Form_2026_05_27_16_08_51_576Item fields.
		/// </summary>
		private readonly Form_2026_05_27_16_08_51_576ItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Student_Name.
		/// </summary>
		[DatabaseField]
		public string Student_Name
		{
			get => ValidationHelper.GetString(GetValue(nameof(Student_Name)), @"");
			set => SetValue(nameof(Student_Name), value);
		}


		/// <summary>
		/// Mobile.
		/// </summary>
		[DatabaseField]
		public string Mobile
		{
			get => ValidationHelper.GetString(GetValue(nameof(Mobile)), @"");
			set => SetValue(nameof(Mobile), value);
		}


		/// <summary>
		/// Email.
		/// </summary>
		[DatabaseField]
		public string Email
		{
			get => ValidationHelper.GetString(GetValue(nameof(Email)), @"");
			set => SetValue(nameof(Email), value);
		}


		/// <summary>
		/// Courses.
		/// </summary>
		[DatabaseField]
		public string Courses
		{
			get => ValidationHelper.GetString(GetValue(nameof(Courses)), @"");
			set => SetValue(nameof(Courses), value);
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Form_2026_05_27_16_08_51_576Item fields.
		/// </summary>
		[RegisterProperty]
		public Form_2026_05_27_16_08_51_576ItemFields Fields
		{
			get => mFields;
		}


		/// <summary>
		/// Provides extended API for working with Form_2026_05_27_16_08_51_576Item fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class Form_2026_05_27_16_08_51_576ItemFields : AbstractHierarchicalObject<Form_2026_05_27_16_08_51_576ItemFields>
		{
			/// <summary>
			/// The content item of type Form_2026_05_27_16_08_51_576Item that is a target of the extended API.
			/// </summary>
			private readonly Form_2026_05_27_16_08_51_576Item mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="Form_2026_05_27_16_08_51_576ItemFields" /> class with the specified content item of type Form_2026_05_27_16_08_51_576Item.
			/// </summary>
			/// <param name="instance">The content item of type Form_2026_05_27_16_08_51_576Item that is a target of the extended API.</param>
			public Form_2026_05_27_16_08_51_576ItemFields(Form_2026_05_27_16_08_51_576Item instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Student_Name.
			/// </summary>
			public string Student_Name
			{
				get => mInstance.Student_Name;
				set => mInstance.Student_Name = value;
			}


			/// <summary>
			/// Mobile.
			/// </summary>
			public string Mobile
			{
				get => mInstance.Mobile;
				set => mInstance.Mobile = value;
			}


			/// <summary>
			/// Email.
			/// </summary>
			public string Email
			{
				get => mInstance.Email;
				set => mInstance.Email = value;
			}


			/// <summary>
			/// Courses.
			/// </summary>
			public string Courses
			{
				get => mInstance.Courses;
				set => mInstance.Courses = value;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Form_2026_05_27_16_08_51_576Item" /> class.
		/// </summary>
		public Form_2026_05_27_16_08_51_576Item() : base(CLASS_NAME)
		{
			mFields = new Form_2026_05_27_16_08_51_576ItemFields(this);
		}

		#endregion
	}
}