//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;

namespace Edukate
{
	/// <summary>
	/// Represents a page of type <see cref="InstructorItem"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class InstructorItem : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Edukate.InstructorItem";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// Name.
		/// </summary>
		public string Name { get; set; }


		/// <summary>
		/// Designation.
		/// </summary>
		public string Designation { get; set; }


		/// <summary>
		/// Bio.
		/// </summary>
		public string Bio { get; set; }


		/// <summary>
		/// Photo.
		/// </summary>
		public IEnumerable<Images> Photo { get; set; }


		/// <summary>
		/// FacebookURL.
		/// </summary>
		public string FacebookURL { get; set; }


		/// <summary>
		/// TwitterURL.
		/// </summary>
		public string TwitterURL { get; set; }


		/// <summary>
		/// LinkedInURL.
		/// </summary>
		public string LinkedInURL { get; set; }


		/// <summary>
		/// InstagramURL.
		/// </summary>
		public string InstagramURL { get; set; }


		/// <summary>
		/// YoutubeURL.
		/// </summary>
		public string YoutubeURL { get; set; }
	}
}