//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Edukate
{
	/// <summary>
	/// Represents a content item of type <see cref="Announcements"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Announcements : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Edukate.Announcements";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// Announcement_Title.
		/// </summary>
		public string Announcement_Title { get; set; }


		/// <summary>
		/// Announcement_Image.
		/// </summary>
		public IEnumerable<Images> Announcement_Image { get; set; }


		/// <summary>
		/// Publish_Date.
		/// </summary>
		public DateTime Publish_Date { get; set; }


		/// <summary>
		/// Short_Description.
		/// </summary>
		public string Short_Description { get; set; }
	}
}