//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Edukate
{
	/// <summary>
	/// Represents a content item of type <see cref="CourseCards"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class CourseCards : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Edukate.CourseCards";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// CourseName.
		/// </summary>
		public string CourseName { get; set; }


		/// <summary>
		/// Instructor.
		/// </summary>
		public string Instructor { get; set; }


		/// <summary>
		/// Rating.
		/// </summary>
		public double Rating { get; set; }


		/// <summary>
		/// CourseImage.
		/// </summary>
		public ContentItemAsset CourseImage { get; set; }
	}
}