//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;

namespace Edukate
{
	/// <summary>
	/// Represents a page of type <see cref="CourseItem"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class CourseItem : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Edukate.CourseItem";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// Title.
		/// </summary>
		public string Title { get; set; }


		/// <summary>
		/// CourseTitle.
		/// </summary>
		public string CourseTitle { get; set; }


		/// <summary>
		/// CourseData.
		/// </summary>
		public string CourseData { get; set; }


		/// <summary>
		/// CourseImage.
		/// </summary>
		public IEnumerable<Images> CourseImage { get; set; }


		/// <summary>
		/// Duration.
		/// </summary>
		public string Duration { get; set; }


		/// <summary>
		/// SlugURL.
		/// </summary>
		public string SlugURL { get; set; }


		/// <summary>
		/// Instructor.
		/// </summary>
		public string Instructor { get; set; }
	}
}