//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;

namespace Edukate
{
	/// <summary>
	/// Represents a page of type <see cref="Course"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Course : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Edukate.Course";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// CourseName.
		/// </summary>
		public string CourseName { get; set; }


		/// <summary>
		/// Description.
		/// </summary>
		public string Description { get; set; }


		/// <summary>
		/// Duration.
		/// </summary>
		public string Duration { get; set; }


		/// <summary>
		/// Eligibility.
		/// </summary>
		public string Eligibility { get; set; }


		/// <summary>
		/// Fees.
		/// </summary>
		public int Fees { get; set; }


		/// <summary>
		/// Department.
		/// </summary>
		public string Department { get; set; }


		/// <summary>
		/// Image.
		/// </summary>
		public IEnumerable<Images> Image { get; set; }
	}
}